"""empty message

Revision ID: 8a554cb4820e
Revises: 
Create Date: 2022-02-11 23:25:14.909679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8a554cb4820e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("account_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "account_type",
            sa.Enum("merchant", "personal", "issuer", name="acc_type"),
            nullable=False,
        ),
        sa.Column("balance", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("account_id"),
    )
    op.create_table(
        "merchants",
        sa.Column("merchant_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("account_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("merchant_name", sa.String(length=200), nullable=False),
        sa.Column("merchant_url", sa.String(length=200), nullable=False),
        sa.Column("apiKey", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.account_id"],
        ),
        sa.PrimaryKeyConstraint("merchant_id"),
    )
    op.create_table(
        "transactions",
        sa.Column("transaction_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("merchant_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("incomeAccount", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("outcomeAccount", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("extraData", sa.String(length=255), nullable=True),
        sa.Column("signature", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "CREATE",
                "CONFIRM",
                "VERIFY",
                "CANCEL",
                "EXPIRE",
                "SUCCESS",
                name="transaction_status",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["incomeAccount"],
            ["accounts.account_id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.merchant_id"],
        ),
        sa.ForeignKeyConstraint(
            ["outcomeAccount"],
            ["accounts.account_id"],
        ),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    op.drop_table("merchants")
    op.drop_table("accounts")
    # ### end Alembic commands ###
