"""empty message

Revision ID: c440834b75e8
Revises: 
Create Date: 2022-02-17 21:54:33.346764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c440834b75e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('transaction_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('merchant_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('incomeAccount', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('outcomeAccount', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('extraData', sa.String(length=255), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('INITIALIZED', 'CONFIRMED', 'VERIFYED', 'CANCELED', 'EXPIRED', 'FAILED', 'COMPLETED', name='transactions_status'), nullable=False),
    sa.ForeignKeyConstraint(['incomeAccount'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.ForeignKeyConstraint(['outcomeAccount'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
